version: '3.9'

services:
  eureka-server:
    image: eureka-server:latest
    ports:
      - "8761:8761"

  inventory-service:
    image: inventory-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

