version: '3.9'
services:
  eureka-server:
    build:
      context: ./eurekaServerApplication
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  ticketing-service:
    build:
      context: ./ticketingservice
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server

  inventory-management-service:
    build:
      context: ./inventorymanagementservice
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server

  my-nginx-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - ticketing-service
      - inventory-management-service
